### ISSUE TITLE
sendtoaddress issue

### ISSUE THREAD

**Issue by pinpins** [campuscoindev/CC#2]
something wrong with wallet daemon
getwalletinfo
{
    "walletversion": 61000,
    "balance": 4509.9998372,
    "txcount": 2173,
    "keypoololdest": "2019-04-05 16:39:46 +0300",
    "keypoolsize": 1001
}
sendtoaddress CfVPpdGu7p4ifDquEY2r8CozgwtjUoh8ar 1000
 
error -4: insufficient funds.

**Comment by SmartGuyy** [comment]
Did you try on latest desktop wallet ?

**Comment by pinpins** [comment]
no, I am running daemon at pool

**Comment by SmartGuyy** [comment]
Try to extract your private key to most recent desktop wallet. Also note that in current version of desktop wallet, staking must be disabled in your conf or you will get this error "error -4: insufficient funds".
